name: authentication_buttons
description: To effortlessly add social media login buttons to any flutter app, use the Authentication Buttons flutter package.
version: 0.0.5
homepage: https://github.com/shivamshashank/authentication_buttons
repository: https://github.com/shivamshashank/authentication_buttons
issue_tracker: https://github.com/shivamshashank/authentication_buttons/issues
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:

  assets:
    - lib/assets/images/